name: savi_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.5+1
  # Base de Datos (PostgreSQL en la nube)
  supabase_flutter: ^2.0.0
  intl: ^0.20.2
  qr_flutter: ^4.1.0
  share_plus: ^12.0.1
  image_picker: ^0.8.7+5
  flutter_svg: ^2.0.7
  mime: ^1.0.3
  shared_preferences: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/1.png
    - assets/2.png
    - assets/3.png
    - assets/logo.png
    - assets/logo2.png
    - assets/logo2.svg
    - assets/4.png
    - assets/5.png